"""Filesystem-backed `StorageBackend`. Ported hardening pattern from
UrraHosting-WebPanel's `services/storage.py`: every write/read/delete
opens its target with `os.open(..., O_NOFOLLOW, dir_fd=parent_fd)`
instead of resolving a path once and trusting it, so a symlink swapped
into the shard directory between check and use fails closed instead of
following it (classic TOCTOU).

The path-traversal surface here is much smaller than WebPanel's
category+relative-path browser: every filename this module ever opens
is a `str(uuid.UUID)` generated by the application (Node.id /
FileVersion.id), never something derived from a user-supplied filename.
The hardening is kept anyway as defense in depth (a bug elsewhere that
lets an attacker forge a `blob_id` should still fail closed).
"""

from __future__ import annotations

import hashlib
import os
import uuid
from pathlib import Path
from typing import BinaryIO

from .base import FileStat, StorageBackend, StorageError

_NOFOLLOW = getattr(os, "O_NOFOLLOW", 0)
_CHUNK = 1024 * 1024


def _shard(root: Path, hex_id: str) -> Path:
    return root / hex_id[:2]


def _open_dir_fd(path: Path) -> int:
    path.mkdir(parents=True, exist_ok=True)
    return os.open(path, os.O_RDONLY | os.O_DIRECTORY | _NOFOLLOW)


def _write_atomic(dir_fd: int, final_name: str, stream: BinaryIO, max_bytes: int) -> FileStat:
    tmp_name = f".{final_name}.part"
    try:
        os.unlink(tmp_name, dir_fd=dir_fd)
    except FileNotFoundError:
        pass

    flags = os.O_WRONLY | os.O_CREAT | os.O_TRUNC | _NOFOLLOW
    tmp_fd = os.open(tmp_name, flags, 0o600, dir_fd=dir_fd)
    digest = hashlib.sha256()
    written = 0
    try:
        with os.fdopen(tmp_fd, "wb") as handle:
            while True:
                chunk = stream.read(_CHUNK)
                if not chunk:
                    break
                written += len(chunk)
                if written > max_bytes:
                    raise StorageError("El archivo excede el tamano maximo permitido")
                digest.update(chunk)
                handle.write(chunk)
    except Exception:
        try:
            os.unlink(tmp_name, dir_fd=dir_fd)
        except FileNotFoundError:
            pass
        raise

    try:
        st = os.stat(final_name, dir_fd=dir_fd, follow_symlinks=False)
        import stat as stat_module

        if stat_module.S_ISLNK(st.st_mode):
            os.unlink(tmp_name, dir_fd=dir_fd)
            raise StorageError("No se permite escribir sobre un symlink")
    except FileNotFoundError:
        pass

    os.rename(tmp_name, final_name, src_dir_fd=dir_fd, dst_dir_fd=dir_fd)
    return FileStat(size_bytes=written, checksum_sha256=digest.hexdigest())


def _open_read(dir_fd: int, name: str) -> BinaryIO:
    flags = os.O_RDONLY | _NOFOLLOW
    try:
        fd = os.open(name, flags, dir_fd=dir_fd)
    except OSError as exc:
        raise StorageError("Archivo no encontrado") from exc
    return os.fdopen(fd, "rb")


def _delete(dir_fd: int, name: str) -> None:
    try:
        os.unlink(name, dir_fd=dir_fd)
    except FileNotFoundError:
        pass


class LocalFsBackend(StorageBackend):
    def __init__(self, blobs_root: Path, versions_root: Path):
        self._blobs_root = Path(blobs_root)
        self._versions_root = Path(versions_root)
        self._blobs_root.mkdir(parents=True, exist_ok=True)
        self._versions_root.mkdir(parents=True, exist_ok=True)

    def save(self, blob_id: uuid.UUID, stream: BinaryIO, max_bytes: int) -> FileStat:
        hex_id = str(blob_id)
        shard = _shard(self._blobs_root, hex_id)
        dir_fd = _open_dir_fd(shard)
        try:
            return _write_atomic(dir_fd, f"{hex_id}.bin", stream, max_bytes)
        finally:
            os.close(dir_fd)

    def open(self, blob_id: uuid.UUID) -> BinaryIO:
        hex_id = str(blob_id)
        shard = _shard(self._blobs_root, hex_id)
        dir_fd = _open_dir_fd(shard)
        try:
            return _open_read(dir_fd, f"{hex_id}.bin")
        finally:
            os.close(dir_fd)

    def delete(self, blob_id: uuid.UUID) -> None:
        hex_id = str(blob_id)
        shard = _shard(self._blobs_root, hex_id)
        dir_fd = _open_dir_fd(shard)
        try:
            _delete(dir_fd, f"{hex_id}.bin")
        finally:
            os.close(dir_fd)

    def save_version(self, node_id: uuid.UUID, version_id: uuid.UUID, stream: BinaryIO, max_bytes: int) -> FileStat:
        node_dir = self._versions_root / str(node_id)
        dir_fd = _open_dir_fd(node_dir)
        try:
            return _write_atomic(dir_fd, f"{version_id}.bin", stream, max_bytes)
        finally:
            os.close(dir_fd)

    def open_version(self, node_id: uuid.UUID, version_id: uuid.UUID) -> BinaryIO:
        node_dir = self._versions_root / str(node_id)
        dir_fd = _open_dir_fd(node_dir)
        try:
            return _open_read(dir_fd, f"{version_id}.bin")
        finally:
            os.close(dir_fd)

    def delete_version(self, node_id: uuid.UUID, version_id: uuid.UUID) -> None:
        node_dir = self._versions_root / str(node_id)
        dir_fd = _open_dir_fd(node_dir)
        try:
            _delete(dir_fd, f"{version_id}.bin")
        finally:
            os.close(dir_fd)
